### ISSUE TITLE
Bug: User Mentions 

### ISSUE THREAD

**Issue by DracoClaw** [powercord-community/rolecolor-everywhere#28] opened 2021-09-03 13:29 UTC
The color for user mentions is being pulled from the top role, and not the top role with a color. 

This user mention should be Red like the role, but it is the default role color like the Team D role. 
![image](https://user-images.githubusercontent.com/34274162/132012944-d2a0187a-cbb1-479a-96fc-bc4f0ea75206.png)

**Comment by DracoClaw** [comment] 2021-09-03 13:32
Actually seems its just not working for anyone.

![image](https://user-images.githubusercontent.com/34274162/132013480-7a91e626-b9ef-4f3b-bf70-ba3a606fb93b.png)

**Comment by cyyynthia** [comment] 2021-09-03 13:34
Duplicate of #26, #27

**Closed as completed by cyyynthia** 2021-09-03 13:34 UTC
Labels: bug, duplicate, invalid
