### ISSUE TITLE
Mentions are uncolored

### ISSUE THREAD

**Issue by AtlasTheProto** [powercord-community/rolecolor-everywhere#27] opened 2021-08-27 23:31 UTC
This issue was previously fixed with https://github.com/powercord-community/rolecolor-everywhere/commit/8cc064f5704045e654dac7af0110d9b9cdda75de, but has recently cropped up again.

Enabled:
![image](https://user-images.githubusercontent.com/17933206/131197975-9c4d7c88-c34b-4292-9d08-01c6834c6799.png)

Disabled:
![image](https://user-images.githubusercontent.com/17933206/131197986-f5264001-c294-4933-9894-8f88b6c1260a.png)

Error: 
![image](https://user-images.githubusercontent.com/17933206/131198032-78df830d-2a72-4697-aed0-188c03a6b07c.png)

**Comment by cyyynthia** [comment] 2021-08-27 23:43
Duplicate of #26

**Closed as completed by cyyynthia** 2021-08-27 23:43 UTC
Labels: bug, duplicate, invalid
