### ISSUE TITLE
Anyone with a colored role doesn't show color on pings

### ISSUE THREAD

**Issue by Nyxgawr** [powercord-community/rolecolor-everywhere#26] opened 2021-08-16 04:10 UTC
I've updated to the latest version, and it's not coloring the ping. I saw that it was an issue before, and was labeled as fixed, but I'm still having the same problem. I've checked the settings of the plugin, and the "Mentions" setting was turned on.
<img width="226" alt="color ping role test" src="https://user-images.githubusercontent.com/30098427/129510305-a223f16c-77ba-444d-abd8-8b28622b447e.png">

**Comment by cyyynthia** [comment] 2021-08-20 23:15
I cannot reproduce this bug. What is the version of your plugin & Powercord?

**Comment by Nyxgawr** [comment] 2021-08-20 23:32
I'm still relatively new to Powercord, so I don't know where to check for that. I had just downloaded the plugin from here a week ago.

**Comment by cyyynthia** [comment] 2021-08-20 23:41
You can find your Powercord version in `Settings > Updater > Top left`
You can find the plugin version by going in `Settings > Plugins` and looking for the plugin (you can use the handy search bar there)

**Comment by Nyxgawr** [comment] 2021-08-20 23:46
It says I'm on Revision 2a5b9fa, and the plugin is on 1.2.1.

**Comment by cyyynthia** [comment] 2021-08-20 23:49
Did you download the plugin as a zip file? If you did, this isn't the right way of installing plugins on Powercord as they do not receive updates; refer to the plugin-support channel for the correct procedure

**Comment by Nyxgawr** [comment] 2021-08-20 23:54
So I've removed the plugin from my folder, got the plugin correctly, restarted Discord, enabled the plugin, and it's still having this issue. the plugin is now on 1.2.2.

**Comment by cyyynthia** [comment] 2021-08-21 12:36
I tried again and still cannot reproduce the issue. Do you have any theme, quickcss snippet or a plugin likely to interfere with the functionality of the plugin?

**Comment by Nyxgawr** [comment] 2021-08-22 02:10
So, after going through my plugins and turning them all off, I've found out that Double Click Voice Channels breaks Rolecolor Everywhere.

**Comment by cyyynthia** [comment] 2021-08-22 12:57
And it seems to correlate, [this PR](https://github.com/Twizzer/VC-Double-Click-Join/pull/4) removed important code required in order for other plugins to function. Since this is out of the reach of this plugin and something that needs to be fixed there, I'll be closing this issue.

**Closed as completed by cyyynthia** 2021-08-22 12:57 UTC
Labels: bug, invalid

**Comment by D3SOX** [comment] 2021-08-30 14:11
@cyyynthia This was the first time I did something with Powercord plugins. Can you tell me what important code I removed?

**Comment by D3SOX** [comment] 2021-08-30 15:15
I think I fixed it with the new PR.
Is this plugin supposed to also change the color of the text message, or did I mess something up again?

![image](https://user-images.githubusercontent.com/24937357/131361947-2cc26c0c-856e-47f0-80a9-aeb16ff46a7f.png)

**Comment by cyyynthia** [comment] 2021-08-30 15:45
Yes the plugin adds coloring to messages (configurable, but by default everything is open). The PR will also resolve the compatibility issues.

The important code was indeed the displayName part, which your PR adds back (it was the goal of the Object.assign invocation that you removed in your previous PR).

**Comment by D3SOX** [comment] 2021-08-30 15:47
Thank you, I understand how to correctly inject something now.
